pull_request_rules:
  - name: automatic merge and new release from cloudalchemybot
    conditions:
      - "status-success=Travis CI - Pull Request"
      - status-success=WIP
      - head=autoupdate
      - author=cloudalchemybot
    actions:
      merge:
        method: squash
  - name: automatic merge repository sync from cloudalchemybot
    conditions:
      - "status-success=Travis CI - Pull Request"
      - status-success=WIP
      - head=skeleton
      - author=cloudalchemybot
    actions:
      merge:
        method: squash
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
