---
- name: Copy configuration file
  template:
    src: "{{ coredns_config_file }}"
    dest: /etc/coredns/Corefile
    owner: root
    group: root
    mode: 0644
  notify: restart coredns

- name: Copy zone files
  template:
    src: "{{ item }}"
    dest: /etc/coredns/zones
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - coredns/zones/*
